#!/usr/bin/env php
<?php

// 1. Cargar Autoloaders
$internalAutoloader = __DIR__ . '/vendor/autoload.php';
$currentAutoloader = getcwd() . '/vendor/autoload.php';

if (file_exists($internalAutoloader)) {
    require $internalAutoloader;
} elseif (file_exists($currentAutoloader)) {
    require $currentAutoloader;
} else {
    die("❌ Error: No se encontró 'vendor/autoload.php'.\n");
}

// 2. Ejecutar el Kernel
use Framework\Console\Kernel;

$kernel = new Kernel();
$kernel->handle($argv);